steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
  # Build the static website
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
# Store the generated static content as artifacts
artifacts:
  objects:
    location: 'gs://sumbuddy-docs-site/'
    paths: ['build/**']
options:
  logging: CLOUD_LOGGING_ONLY
