steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm:20'
    args: ['install']
  # Build the static website
  - name: 'gcr.io/cloud-builders/npm:20'
    args: ['run', 'build']
# Store the generated static content as artifacts
artifacts:
  objects:
    location: 'gs://sumbuddy-docs-site/docs'
    paths: ['build/**']
options:
  logging: CLOUD_LOGGING_ONLY
