steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
  # Build the static website
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
# Store the generated static content as artifacts
  # Deploy to GCS
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'storage'
      - 'rsync'
      - '--delete'
      - 'build/'
      - 'gs://sumbuddy-docs-site'
options:
  logging: CLOUD_LOGGING_ONLY
